import { api } from './api'
import { CATEGORIES, MARKET_PRICE_RANGES } from '../constants'
const SORTERS = { price_low:(a,b)=>a.price-b.price, rating_high:(a,b)=>(b.farmer?.rating??0)-(a.farmer?.rating??0), nearest:(a,b)=>(a.farmer?.distanceKm??Infinity)-(b.farmer?.distanceKm??Infinity), recent:(a,b)=>new Date(b.createdAt)-new Date(a.createdAt), quantity_high:(a,b)=>b.availableQuantity-a.availableQuantity }
const withBestPriceFlags = (list) => { const lowest = new Map(); list.forEach(p => { if (!lowest.has(p.name) || p.price < lowest.get(p.name)) lowest.set(p.name,p.price) }); return list.map(p=>({...p,isBestPrice:p.price===lowest.get(p.name)})) }
export function getProducts({ category, query, sortBy='recent' }={}) { return api.get('/products').then(r=>{ let list=r.data; if(category&&category!=='All') list=list.filter(p=>p.category===category); if(query){const q=query.trim().toLowerCase(); list=list.filter(p=>[p.name,p.farmer?.name,p.farmer?.farmName].some(v=>String(v||'').toLowerCase().includes(q)))} return withBestPriceFlags(list).sort(SORTERS[sortBy]||SORTERS.recent) }) }
export function getProductDetails(id) { return Promise.all([api.get(`/products/${id}`), api.get('/products')]).then(([one, all]) => { const product=one.data; const siblings=withBestPriceFlags(all.data.filter(p=>p.name===product.name)); const lowest=Math.min(...siblings.map(p=>p.price)); const highest=Math.max(...siblings.map(p=>p.farmer?.rating??0)); return {product,comparison:siblings.map(p=>({...p,isLowestPrice:p.price===lowest,isHighestRating:(p.farmer?.rating??0)===highest}))} }) }
export function getProductsForFarmer(farmerId) { return api.get(`/farmers/${farmerId}/products`).then(r=>r.data) }
export function createProduct(formValues) { return api.post('/products', formValues).then(r=>r.data) }
export function updateProduct(productId, formValues) { return api.patch(`/products/${productId}`, formValues).then(r=>r.data) }
export function deleteProduct(productId) { return api.delete(`/products/${productId}`).then(r=>r.data) }
export function getCategories() { return CATEGORIES }
export function getMarketPriceRanges() { return Promise.resolve(MARKET_PRICE_RANGES) }
export function searchAll(query) { return Promise.all([api.get('/products'), api.get('/farmers'), api.get('/fpos')]).then(([p,f,o])=>{const q=query.trim().toLowerCase(); if(!q)return {products:[],farmers:[],fpos:[]}; return {products:p.data.filter(x=>[x.name,x.farmer?.name,x.farmer?.farmName].some(v=>String(v||'').toLowerCase().includes(q))),farmers:f.data.filter(x=>[x.name,x.farmName,x.location?.city,x.location?.state].some(v=>String(v||'').toLowerCase().includes(q))),fpos:o.data.filter(x=>[x.name,x.location?.city,x.location?.state].some(v=>String(v||'').toLowerCase().includes(q)))} }) }
