import { createHmac, pbkdf2Sync, randomBytes, timingSafeEqual } from 'node:crypto'
import { DatabaseSync } from 'node:sqlite'
import { createServer } from 'node:http'
import { mkdirSync, existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dbPath = process.env.DATABASE_PATH || join(root, 'data', 'khet2kart.sqlite')
mkdirSync(dirname(dbPath), { recursive: true })
const dbExisted = existsSync(dbPath)
const db = new DatabaseSync(dbPath)
if (!dbExisted) db.exec(readFileSync(join(root, 'data', 'khet2kart.sql'), 'utf8'))
const port = Number(process.env.PORT || 4000)
const secret = process.env.JWT_SECRET || 'replace-this-development-secret-before-deploying'

function run(sql, ...values) { return db.prepare(sql).run(...values) }
function one(sql, ...values) { return db.prepare(sql).get(...values) }
function all(sql, ...values) { return db.prepare(sql).all(...values) }
function json(value, fallback = null) { try { return JSON.parse(value) } catch { return fallback } }
function hash(password, salt = randomBytes(16).toString('hex')) { return `${salt}:${pbkdf2Sync(password, salt, 120000, 32, 'sha256').toString('hex')}` }
function validPassword(password, stored) { const [salt, digest] = stored.split(':'); const candidate = hash(password, salt).split(':')[1]; return timingSafeEqual(Buffer.from(candidate), Buffer.from(digest)) }
function tokenFor(user) { const payload = Buffer.from(JSON.stringify({ id: user.id, role: user.role, exp: Date.now() + 7 * 86400000 })).toString('base64url'); return `${payload}.${createHmac('sha256', secret).update(payload).digest('base64url')}` }
function currentUser(req) { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return null; const [payload, signature] = token.split('.'); const expected = createHmac('sha256', secret).update(payload).digest('base64url'); if (!signature || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; const value = json(Buffer.from(payload, 'base64url').toString()); return value?.exp > Date.now() ? one('SELECT id,name,email,role,linked_id AS linkedId,is_premium AS isPremium,premium_renewal_date AS premiumRenewalDate,premium_auto_renew AS premiumAutoRenew,consumer_location AS consumerLocation FROM users WHERE id = ?', value.id) : null }
const allowedOrigins = (process.env.CLIENT_ORIGIN || 'http://localhost:5173,https://khet-kart-tau.vercel.app')
  .split(',')
  .map((origin) => origin.trim().replace(/\/$/, ''))
  .filter(Boolean)

function send(res, status, body, req = null) {
  const request = req || res._khetRequest
  const requestOrigin = request?.headers?.origin?.replace(/\/$/, '')
  const corsOrigin = requestOrigin && allowedOrigins.includes(requestOrigin) ? requestOrigin : allowedOrigins[0]
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': corsOrigin,
    'Vary': 'Origin',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, OPTIONS'
  })
  res.end(JSON.stringify(body))
}
async function body(req) { let raw = ''; for await (const part of req) raw += part; try { return raw ? JSON.parse(raw) : {} } catch { throw new Error('Invalid JSON request body') } }
function requireUser(req, res) { const user = currentUser(req); if (!user) { send(res, 401, { message: 'Authentication required' }); return null } return user }
function initialize() {
  db.exec(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE,aadhaar TEXT UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('farmer','consumer','fpo')),linked_id INTEGER,is_premium INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,consumer_location TEXT);
  CREATE TABLE IF NOT EXISTS farmer_profiles (user_id INTEGER PRIMARY KEY,farm_name TEXT,location TEXT,crops TEXT,rating REAL DEFAULT 0,verified INTEGER DEFAULT 0,distance_km REAL DEFAULT 0);
  CREATE TABLE IF NOT EXISTS fpo_profiles (user_id INTEGER PRIMARY KEY,fpo_name TEXT,representative TEXT,location TEXT,member_count INTEGER DEFAULT 0);
  CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT NOT NULL,price REAL NOT NULL CHECK(price >= 0),unit TEXT NOT NULL,available_quantity REAL NOT NULL CHECK(available_quantity >= 0),quality_grade TEXT,image TEXT,harvest_date TEXT,availability_date TEXT,description TEXT,farmer_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY,group_id TEXT NOT NULL,consumer_id INTEGER NOT NULL,buyer_name TEXT NOT NULL,status TEXT NOT NULL,delivery_fee REAL NOT NULL DEFAULT 0,platform_fee REAL NOT NULL DEFAULT 0,total_amount REAL NOT NULL,payment_method TEXT NOT NULL DEFAULT 'upi',placed_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS order_items (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL,product_id INTEGER NOT NULL,farmer_id INTEGER NOT NULL,quantity REAL NOT NULL,price REAL NOT NULL);
  CREATE TABLE IF NOT EXISTS reviews (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT,farmer_id INTEGER NOT NULL,product_id INTEGER,consumer_id INTEGER,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),comment TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS pooled_lots (id TEXT PRIMARY KEY,fpo_id INTEGER NOT NULL,product_name TEXT NOT NULL,quality_grade TEXT,sale_price REAL,status TEXT NOT NULL,contributions TEXT NOT NULL,verification TEXT,logistics TEXT,created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS demand_requests (id TEXT PRIMARY KEY,product_name TEXT NOT NULL,buyer_name TEXT NOT NULL,required_quantity REAL NOT NULL,unit TEXT NOT NULL,preferred_price_low REAL,preferred_price_high REAL,location TEXT,required_by TEXT,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS logistics_routes (id TEXT PRIMARY KEY,order_id TEXT NOT NULL,pickup_locations TEXT,destination TEXT,transport_partner TEXT,estimated_distance_km REAL,estimated_delivery_minutes REAL,route_efficiency REAL,status TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`)
  const columns = all('PRAGMA table_info(orders)').map((c) => c.name)
  if (!columns.includes('payment_method')) db.exec("ALTER TABLE orders ADD COLUMN payment_method TEXT NOT NULL DEFAULT 'upi'")
  if (!columns.includes('delivery_address')) db.exec("ALTER TABLE orders ADD COLUMN delivery_address TEXT")
  const userColumns = all('PRAGMA table_info(users)').map((c) => c.name)
  if (!userColumns.includes('consumer_location')) db.exec("ALTER TABLE users ADD COLUMN consumer_location TEXT")
  if (!userColumns.includes('premium_renewal_date')) db.exec("ALTER TABLE users ADD COLUMN premium_renewal_date TEXT")
  if (!userColumns.includes('premium_auto_renew')) db.exec("ALTER TABLE users ADD COLUMN premium_auto_renew INTEGER NOT NULL DEFAULT 0")
  const reviewColumns = all('PRAGMA table_info(reviews)').map((c) => c.name)
  if (!reviewColumns.includes('order_id')) db.exec("ALTER TABLE reviews ADD COLUMN order_id TEXT")
}
function productRows(where = '', values = []) { return all(`SELECT p.id,p.name,p.category,p.price,p.unit,p.available_quantity AS availableQuantity,p.quality_grade AS qualityGrade,p.image,p.harvest_date AS harvestDate,p.availability_date AS availabilityDate,p.description,p.farmer_id AS farmerId,p.created_at AS createdAt,u.name AS farmerName,fp.farm_name AS farmName,fp.rating,fp.verified,fp.distance_km AS distanceKm,fp.location FROM products p JOIN users u ON u.id=p.farmer_id LEFT JOIN farmer_profiles fp ON fp.user_id=u.id ${where}`, ...values).map((p) => ({ ...p, farmer: { id: p.farmerId, name: p.farmerName, farmName: p.farmName, rating: p.rating, verified: Boolean(p.verified), distanceKm: p.distanceKm, location: json(p.location, {}) } })) }
function orderRows(where = '', values = []) { const rows = all(`SELECT id AS orderId,group_id AS groupId,consumer_id AS consumerId,buyer_name AS buyerName,status,delivery_fee AS deliveryFee,platform_fee AS platformFee,total_amount AS totalAmount,payment_method AS paymentMethod,delivery_address AS deliveryAddress,placed_at AS placedAt FROM orders ${where} ORDER BY placed_at DESC`, ...values); return rows.map((order) => ({ ...order, id: order.orderId, deliveryAddress: json(order.deliveryAddress, null), items: all(`SELECT oi.product_id AS productId,oi.farmer_id AS farmerId,oi.quantity,oi.price,COALESCE(p.name, 'Removed produce') AS productName,COALESCE(p.unit, '') AS unit,p.image,u.name AS farmerName,fp.farm_name AS farmName,fp.location AS farmerLocation FROM order_items oi LEFT JOIN products p ON p.id=oi.product_id LEFT JOIN users u ON u.id=oi.farmer_id LEFT JOIN farmer_profiles fp ON fp.user_id=oi.farmer_id WHERE oi.order_id=?`, order.orderId).map((item)=>({...item,farmer:{id:item.farmerId,name:item.farmerName,farmName:item.farmName,location:json(item.farmerLocation,{})}})) })) }
function farmerRows(where = '', values = []) { return all(`SELECT u.id,u.name,u.email,fp.farm_name AS farmName,fp.location,fp.crops,fp.rating,fp.verified,fp.distance_km AS distanceKm FROM users u JOIN farmer_profiles fp ON fp.user_id=u.id ${where}`, ...values).map((row) => ({ ...row, location: json(row.location, {}), crops: json(row.crops, []) , verified: Boolean(row.verified) })) }
function fpoRows(where = '', values = []) { return all(`SELECT u.id,u.name,u.email,fp.fpo_name AS name,fp.representative,fp.location,fp.member_count AS memberCount FROM users u JOIN fpo_profiles fp ON fp.user_id=u.id ${where}`, ...values).map((row) => ({ ...row, location: json(row.location, {}) })) }
function pooledLotRows(fpoId) { return all(`SELECT * FROM pooled_lots ${fpoId ? 'WHERE fpo_id=?' : ''} ORDER BY created_at DESC`, ...(fpoId ? [fpoId] : [])).map((row) => { const contributions=json(row.contributions,[]).map((c)=>{ const farmer=one('SELECT u.name,fp.location FROM users u LEFT JOIN farmer_profiles fp ON fp.user_id=u.id WHERE u.id=?',c.farmerId); return {...c,farmerName:farmer?.name,farmerLocation:json(farmer?.location,{})} }); return { id:row.id,fpoId:row.fpo_id,productName:row.product_name,qualityGrade:row.quality_grade,salePrice:row.sale_price,status:row.status,contributions,verification:json(row.verification,{}),logistics:json(row.logistics,null),createdAt:row.created_at } }) }
initialize()
const server = createServer(async (req, res) => { res._khetRequest = req; try {
  if (req.method === 'OPTIONS') return send(res, 204, {}, req)
  const url = new URL(req.url, `http://${req.headers.host}`); const path = url.pathname
  if (req.method === 'GET' && (path === '/' || path === '/health' || path === '/api/health')) {
    return send(res, 200, { ok: true, service: 'khet2kart-api', apiBase: '/api' })
  }
  if (req.method === 'POST' && path === '/api/auth/login') { const input = await body(req); const user = one('SELECT * FROM users WHERE lower(email)=lower(?) OR aadhaar=?', input.email || '', String(input.aadhaar || '').replace(/\D/g, '')); if (!user || !validPassword(input.password || '', user.password_hash)) return send(res, 401, { message: 'Invalid Aadhaar/email or password' }); const safe = { id:user.id,name:user.name,email:user.email,role:user.role,linkedId:user.linked_id,isPremium:Boolean(user.is_premium),premiumRenewalDate:user.premium_renewal_date || null,premiumAutoRenew:Boolean(user.premium_auto_renew),consumerLocation:json(user.consumer_location,null) }; return send(res, 200, { user:safe, token:tokenFor(safe) }) }
  if (req.method === 'POST' && path === '/api/auth/register') {
    const input = await body(req)
    if (!['farmer','consumer','fpo'].includes(input.role) || !input.name || !input.password || (input.role === 'farmer' ? !input.aadhaar : !input.email)) {
      return send(res, 400, { message:'Name, password and the required login identifier are required' })
    }
    if (input.email && one('SELECT id FROM users WHERE lower(email)=lower(?)', input.email)) {
      return send(res, 409, { message:'An account with this email already exists' })
    }
    if (input.aadhaar && one('SELECT id FROM users WHERE aadhaar=?', input.aadhaar)) {
      return send(res, 409, { message:'An account with this Aadhaar already exists' })
    }
    const inserted = run('INSERT INTO users (name,email,aadhaar,password_hash,role,is_premium) VALUES (?,?,?,?,?,0)', input.name,input.email || null,input.aadhaar || null,hash(input.password),input.role)
    const id = Number(inserted.lastInsertRowid)
    if (input.role === 'farmer') run('INSERT INTO farmer_profiles (user_id,farm_name,location,crops) VALUES (?,?,?,?)',id,input.farmName || input.name,JSON.stringify({ city:input.location || '', state:'' }),JSON.stringify(Array.isArray(input.crops) ? input.crops : []))
    if (input.role === 'fpo') run('INSERT INTO fpo_profiles (user_id,fpo_name,representative,location,member_count) VALUES (?,?,?,?,?)',id,input.fpoName || input.name,input.representative || input.name,JSON.stringify({ city:input.location || '', state:'' }),Number(input.memberCount || 0))
    const user={id,name:input.name,email:input.email || null,role:input.role,linkedId:id,isPremium:false,premiumRenewalDate:null,premiumAutoRenew:false,consumerLocation:null}
    run('UPDATE users SET linked_id=? WHERE id=?', id,id)
    return send(res, 201, { user:{...user,linkedId:id}, token:tokenFor(user) })
  }
  if (req.method === 'GET' && path === '/api/me') { const user=requireUser(req,res); if (!user) return; const profile=user.role === 'farmer' ? farmerRows('WHERE u.id=?',[user.id])[0] : user.role === 'fpo' ? fpoRows('WHERE u.id=?',[user.id])[0] : user; return send(res,200,{...user,profile}) }
  if (req.method === 'PATCH' && path === '/api/me') { const user=requireUser(req,res); if (!user) return; const input=await body(req); if (input.name) run('UPDATE users SET name=?, email=? WHERE id=?',input.name,input.email || user.email,user.id); if (user.role === 'farmer') run('UPDATE farmer_profiles SET farm_name=?,location=?,crops=? WHERE user_id=?',input.farmName || input.name,JSON.stringify({city:input.location || '',state:''}),JSON.stringify(Array.isArray(input.crops) ? input.crops : String(input.crops || '').split(',').map((crop)=>crop.trim()).filter(Boolean)),user.id); if (user.role === 'fpo') run('UPDATE fpo_profiles SET fpo_name=?,representative=?,location=?,member_count=? WHERE user_id=?',input.name,input.representative || '',JSON.stringify({city:input.location || '',state:''}),Number(input.memberCount || 0),user.id); if (input.consumerLocation) run('UPDATE users SET consumer_location=? WHERE id=?',JSON.stringify(input.consumerLocation),user.id); if (input.isPremium === false) run('UPDATE users SET is_premium=0,premium_renewal_date=NULL,premium_auto_renew=0 WHERE id=?',user.id); return send(res,200,{ok:true}) }
  if (req.method === 'GET' && path === '/api/farmers') return send(res,200,farmerRows())
  if (req.method === 'GET' && /^\/api\/farmers\/\d+$/.test(path)) { const farmer=farmerRows('WHERE u.id=?',[path.split('/').pop()])[0]; return farmer ? send(res,200,{...farmer,listings:productRows('WHERE p.farmer_id=?',[farmer.id])}) : send(res,404,{message:'Farmer not found'}) }
  if (req.method === 'GET' && path === '/api/fpos') return send(res,200,fpoRows())
  if (req.method === 'GET' && /^\/api\/fpos\/\d+$/.test(path)) { const fpo=fpoRows('WHERE u.id=?',[path.split('/').pop()])[0]; return fpo ? send(res,200,fpo) : send(res,404,{message:'FPO not found'}) }
  if (req.method === 'GET' && path === '/api/reviews') { const key=url.searchParams.get('farmerId') ? 'r.farmer_id' : 'r.product_id'; const value=url.searchParams.get('farmerId') || url.searchParams.get('productId'); const rows=all(`SELECT r.id,r.order_id AS orderId,r.consumer_id AS consumerId,r.farmer_id AS farmerId,r.product_id AS productId,r.rating AS overall,r.comment,r.created_at AS createdAt,u.name AS reviewerName FROM reviews r LEFT JOIN users u ON u.id=r.consumer_id ${value ? `WHERE ${key}=?` : ''} ORDER BY r.created_at DESC`,...(value?[value]:[])); return send(res,200,rows) }
  if (req.method === 'POST' && path === '/api/reviews') { const user=requireUser(req,res); if (!user) return; const input=await body(req); if (user.role !== 'consumer' || !input.orderId || !Number.isInteger(Number(input.ratings?.overall))) return send(res,400,{message:'A completed consumer order and rating are required'}); if (one('SELECT id FROM reviews WHERE order_id=? AND consumer_id=?',input.orderId,user.id)) return send(res,409,{message:'This order has already been reviewed'}); const record=run('INSERT INTO reviews (order_id,farmer_id,product_id,consumer_id,rating,comment) VALUES (?,?,?,?,?,?)',input.orderId,input.farmerId,input.productId,user.id,input.ratings.overall,input.comment || ''); return send(res,201,{id:Number(record.lastInsertRowid),...input.ratings,reviewerName:user.name,farmerId:input.farmerId,productId:input.productId,consumerId:user.id,orderId:input.orderId}) }
  if (req.method === 'GET' && path === '/api/fpo-stats') { const fpo=one(`SELECT member_count AS memberCount FROM fpo_profiles WHERE user_id=?`,30); const stats=one(`SELECT COALESCE(SUM(p.available_quantity),0) AS availableSupplyKg FROM users u LEFT JOIN products p ON p.farmer_id=u.id WHERE u.role='farmer'`); const activeLots=one(`SELECT COUNT(*) AS count FROM pooled_lots WHERE status != 'dispatched'`).count; const activeOrders=one(`SELECT COUNT(*) AS count FROM orders WHERE status != 'delivered'`).count; return send(res,200,{registeredFarmers:fpo?.memberCount || 0,availableSupplyKg:stats.availableSupplyKg,activePooledLots:activeLots,activeOrders}) }
  if (req.method === 'GET' && path === '/api/supply-analytics') { const byCategory=all(`SELECT category,COALESCE(SUM(available_quantity),0) AS totalQuantity FROM products GROUP BY category HAVING totalQuantity>0`).map(r=>({category:r.category,totalQuantity:r.totalQuantity})); const byFarmer=farmerRows().map(f=>({farmer:f,totalQuantity:all('SELECT COALESCE(SUM(available_quantity),0) AS q FROM products WHERE farmer_id=?',f.id)[0].q})); return send(res,200,{byCategory,byFarmer}) }
  if (req.method === 'GET' && /^\/api\/supply\//.test(path)) { const name=decodeURIComponent(path.split('/').pop()); const rows=productRows('WHERE lower(p.name)=lower(?)',[name]).map(listing=>({farmer:listing.farmer,productId:listing.id,availableQuantity:listing.availableQuantity,price:listing.price,qualityGrade:listing.qualityGrade})); return send(res,200,rows) }
  if (req.method === 'GET' && path === '/api/demand') { return send(res,200,all('SELECT id,product_name AS productName,buyer_name AS buyerName,required_quantity AS requiredQuantity,unit,preferred_price_low AS preferredPriceLow,preferred_price_high AS preferredPriceHigh,location,required_by AS requiredBy,status FROM demand_requests ORDER BY created_at DESC')) }
  if (req.method === 'GET' && /^\/api\/logistics\//.test(path)) { const orderId=decodeURIComponent(path.split('/').pop()); const row=one('SELECT * FROM logistics_routes WHERE order_id=?',orderId); return row ? send(res,200,{id:row.id,orderId:row.order_id,pickupLocations:json(row.pickup_locations,[]),transportPartner:row.transport_partner,destination:row.destination,estimatedDistanceKm:row.estimated_distance_km,estimatedDeliveryMinutes:row.estimated_delivery_minutes,routeEfficiency:row.route_efficiency,status:row.status}) : send(res,404,{message:'Logistics route not found'}) }
  if (req.method === 'GET' && /^\/api\/fpos\/\d+\/pooled-lots$/.test(path)) return send(res,200,pooledLotRows(path.split('/')[3]))
  if (req.method === 'POST' && path === '/api/pooled-lots') { const user=requireUser(req,res); if (!user) return; const input=await body(req); if (user.role !== 'fpo' || !input.productName || !Array.isArray(input.contributions) || !input.contributions.length) return send(res,400,{message:'Product and at least one contribution are required'}); const id=`PL${Date.now()}`; run('INSERT INTO pooled_lots VALUES (?,?,?,?,?,?,?,?,?,?)',id,user.linkedId,input.productName,input.qualityGrade || 'A',Number(input.salePrice || 0),'pending_verification',JSON.stringify(input.contributions),JSON.stringify({quantityVerified:false,qualityVerified:false,packagingVerified:false}),null,new Date().toISOString().slice(0,10)); return send(res,201,pooledLotRows(user.linkedId).find((lot)=>lot.id===id)) }
  if (req.method === 'PATCH' && /^\/api\/pooled-lots\//.test(path)) { const user=requireUser(req,res); if (!user) return; const id=path.split('/').pop(); const input=await body(req); const lot=one('SELECT * FROM pooled_lots WHERE id=?',id); if (!lot || user.role !== 'fpo' || lot.fpo_id !== user.linkedId) return send(res,404,{message:'Pooled lot not found'}); const verification=input.verification || json(lot.verification,{}); const nextProduct=input.productName ?? lot.product_name; const nextGrade=input.qualityGrade ?? lot.quality_grade; const nextPrice=input.salePrice !== undefined ? Number(input.salePrice) : lot.sale_price; if (!nextProduct || !Number.isFinite(nextPrice) || nextPrice < 0) return send(res,400,{message:'Valid pooled lot details are required'}); const status=verification.quantityVerified && verification.qualityVerified && verification.packagingVerified ? 'ready_for_pickup' : input.logistics ? 'dispatched' : lot.status; run('UPDATE pooled_lots SET product_name=?,quality_grade=?,sale_price=?,verification=?,logistics=?,status=? WHERE id=?',nextProduct,nextGrade,nextPrice,JSON.stringify(verification),JSON.stringify(input.logistics || json(lot.logistics,null)),status,id); return send(res,200,pooledLotRows(user.linkedId).find((row)=>row.id===id)) }
  if (req.method === 'DELETE' && /^\/api\/pooled-lots\//.test(path)) { const user=requireUser(req,res); if (!user) return; const id=path.split('/').pop(); const lot=one('SELECT fpo_id FROM pooled_lots WHERE id=?',id); if (!lot || user.role !== 'fpo' || lot.fpo_id !== user.linkedId) return send(res,404,{message:'Pooled lot not found'}); run('DELETE FROM pooled_lots WHERE id=?',id); return send(res,200,{ok:true,id}) }
  if (req.method === 'POST' && path === '/api/premium/purchase') {
    const user=requireUser(req,res); if (!user) return
    if (user.role !== 'consumer') return send(res,403,{message:'AgriPlus Premium is available for consumer accounts only.'})
    const input=await body(req); const allowedPayments=['upi','card','bank']
    if (!allowedPayments.includes(input.paymentMethod)) return send(res,400,{message:'Choose a valid online payment method.'})
    const current=one('SELECT is_premium,premium_renewal_date FROM users WHERE id=?',user.id)
    const now=new Date(); const existing=current?.premium_renewal_date ? new Date(current.premium_renewal_date) : null
    const base=input.renew && existing && existing > now ? existing : now
    const renewal=new Date(base); renewal.setMonth(renewal.getMonth()+1)
    run('UPDATE users SET is_premium=1,premium_renewal_date=?,premium_auto_renew=0 WHERE id=?',renewal.toISOString(),user.id)
    const updated=one('SELECT id,name,email,role,linked_id AS linkedId,is_premium AS isPremium,premium_renewal_date AS premiumRenewalDate,premium_auto_renew AS premiumAutoRenew,consumer_location AS consumerLocation FROM users WHERE id=?',user.id)
    return send(res,200,{user:{...updated,isPremium:Boolean(updated.isPremium),premiumAutoRenew:Boolean(updated.premiumAutoRenew),consumerLocation:json(updated.consumerLocation,null)},message:input.renew?'Premium renewed successfully.':'Premium activated successfully.'})
  }

  if (req.method === 'GET' && path === '/api/products') return send(res, 200, productRows())
  if (req.method === 'GET' && path === '/api/orders') { const user=requireUser(req,res); if (!user) return; return send(res,200,orderRows(user.role === 'consumer' ? 'WHERE consumer_id=?' : '', user.role === 'consumer' ? [user.id] : [])) }
  if (req.method === 'GET' && /^\/api\/orders\//.test(path)) { const user=requireUser(req,res); if (!user) return; const id=decodeURIComponent(path.split('/').pop()); const order=orderRows('WHERE id=?',[id])[0]; if (!order || (user.role==='consumer' && order.consumerId!==user.id) || (user.role==='farmer' && !order.items.some(i=>Number(i.farmerId)===Number(user.linkedId)))) return send(res,404,{message:'Order not found'}); return send(res,200,order) }
  if (req.method === 'GET' && /^\/api\/products\/\d+$/.test(path)) { const product = productRows('WHERE p.id=?',[path.split('/').pop()])[0]; return product ? send(res,200,product) : send(res,404,{message:'Product not found'}) }
  if (req.method === 'GET' && /^\/api\/farmers\/\d+\/products$/.test(path)) return send(res,200,productRows('WHERE p.farmer_id=?',[path.split('/')[3]]))
  if (req.method === 'POST' && path === '/api/products') { const user=requireUser(req,res); if (!user) return; if (user.role !== 'farmer') return send(res,403,{message:'Only farmers can publish produce'}); const input=await body(req); if (!input.name || !input.category || !input.unit || !Number.isFinite(Number(input.price)) || Number(input.price)<0 || !Number.isFinite(Number(input.quantity)) || Number(input.quantity)<=0) return send(res,400,{message:'Valid product details are required'}); const id=run('INSERT INTO products (name,category,price,unit,available_quantity,quality_grade,image,harvest_date,availability_date,description,farmer_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)',input.name,input.category,Number(input.price),input.unit,Number(input.quantity),input.qualityGrade || 'A',input.image || '',input.harvestDate || null,input.availabilityDate || null,input.description || '',user.linkedId).lastInsertRowid; return send(res,201,productRows('WHERE p.id=?',[id])[0]) }
  if (req.method === 'PATCH' && /^\/api\/products\/\d+$/.test(path)) { const user=requireUser(req,res); if (!user) return; const id=Number(path.split('/').pop()); const existing=one('SELECT farmer_id FROM products WHERE id=?',id); if (!existing || user.role !== 'farmer' || existing.farmer_id !== user.linkedId) return send(res,404,{message:'Product not found'}); const input=await body(req); if (!input.name || !input.category || !input.unit || !Number.isFinite(Number(input.price)) || Number(input.price)<0 || !Number.isFinite(Number(input.quantity)) || Number(input.quantity)<0) return send(res,400,{message:'Valid product details are required'}); run('UPDATE products SET name=?,category=?,price=?,unit=?,available_quantity=?,quality_grade=?,image=?,harvest_date=?,availability_date=? WHERE id=?',input.name,input.category,Number(input.price),input.unit,Number(input.quantity),input.qualityGrade || 'A',input.image || '',input.harvestDate || null,input.availabilityDate || null,id); return send(res,200,productRows('WHERE p.id=?',[id])[0]) }
  if (req.method === 'DELETE' && /^\/api\/products\/\d+$/.test(path)) { const user=requireUser(req,res); if (!user) return; const id=Number(path.split('/').pop()); const existing=one('SELECT farmer_id FROM products WHERE id=?',id); if (!existing || user.role!=='farmer' || existing.farmer_id!==user.linkedId) return send(res,404,{message:'Product not found'}); run('DELETE FROM products WHERE id=?',id); return send(res,200,{ok:true,id}) }
  if (req.method === 'POST' && path === '/api/orders') { const user=requireUser(req,res); if (!user) return; if (user.role !== 'consumer') return send(res,403,{message:'Only consumers can place orders'}); const input=await body(req); const allowedPayments=['upi','card','bank']; if (!allowedPayments.includes(input.paymentMethod)) return send(res,400,{message:'Choose a valid online payment method.'}); if (!input.deliveryAddress || !input.deliveryAddress.city) return send(res,400,{message:'A delivery address is required.'}); if (!Array.isArray(input.groupedByFarmer) || !input.groupedByFarmer.length) return send(res,400,{message:'Cart is empty'}); const groupId=`ORD${Date.now()}${Math.floor(Math.random()*1000)}`; const results=[]; db.exec('BEGIN'); try { const feeShare=input.groupedByFarmer.length||1; for (const [index,group] of input.groupedByFarmer.entries()) { const id=`${groupId}-${index+1}`; const items=group.items||[]; if(!items.length) throw new Error('An order group is empty.'); let subtotal=0; for(const item of items){ const product=one('SELECT id,name,unit,available_quantity AS availableQuantity,price,farmer_id AS farmerId FROM products WHERE id=?',Number(item.product.id)); if(!product) throw new Error('A product in your cart is no longer available.'); const quantity=Number(item.quantity); const kg=product.unit==='quintal'?quantity*100:quantity; if(kg<10) throw new Error(`${product.name} requires a minimum order of 10 kg.`); if(quantity<=0 || quantity>product.availableQuantity) throw new Error(`Only ${product.availableQuantity} ${product.unit} of ${product.name} is available.`); subtotal += quantity*product.price; } const delivery=Number(input.deliveryFee||0)/feeShare, platform=Number(input.platformFee||0)/feeShare; const total=subtotal+delivery+platform; run('INSERT INTO orders (id,group_id,consumer_id,buyer_name,status,delivery_fee,platform_fee,total_amount,payment_method,delivery_address,placed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',id,groupId,user.id,input.buyerName||user.name,'received',delivery,platform,total,input.paymentMethod,JSON.stringify(input.deliveryAddress),new Date().toISOString()); for(const item of items){ const product=one('SELECT id,farmer_id,price FROM products WHERE id=?',Number(item.product.id)); const quantity=Number(item.quantity); const updated=run('UPDATE products SET available_quantity=available_quantity-? WHERE id=? AND available_quantity>=?',quantity,product.id,quantity); if(!updated.changes) throw new Error('Inventory changed while placing the order. Please review your cart.'); run('INSERT INTO order_items (order_id,product_id,farmer_id,quantity,price) VALUES (?,?,?,?,?)',id,product.id,product.farmer_id,quantity,product.price) } results.push(orderRows('WHERE id=?',[id])[0]) } db.exec('COMMIT'); return send(res,201,{groupId,orders:results,order:results[0],message:'Order placed successfully'}) } catch(error) { db.exec('ROLLBACK'); throw error } }
  return send(res,404,{message:'Route not found'})
} catch (error) { console.error(error); return send(res,500,{message:error.message || 'Unexpected server error'}) } })
server.listen(port, () => console.log(`KHET2KART API listening on http://localhost:${port}`))
